# Generated by Django 5.1.3 on 2024-12-04 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendance',
            old_name='aName',
            new_name='aId',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='attendance',
        ),
        migrations.AddField(
            model_name='attendance',
            name='count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='attendance',
            name='last_checked',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='aDate',
            field=models.DateTimeField(auto_now=True, max_length=100),
        ),
    ]
