# Generated by Django 5.1.3 on 2024-12-05 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_remove_attendance_id_alter_attendance_aid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='last_checked',
        ),
        migrations.AlterField(
            model_name='attendance',
            name='aDate',
            field=models.DateField(auto_now=True, max_length=100),
        ),
    ]
