# Generated by Django 5.1.3 on 2024-12-05 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_remove_attendance_last_checked_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='aDate',
            field=models.DateField(max_length=100),
        ),
    ]
