# Generated by Django 5.1.3 on 2024-12-05 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0005_alter_attendance_adate'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='aNumber',
            field=models.IntegerField(default=0),
        ),
    ]
