# Generated by Django 5.1.3 on 2024-12-13 04:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodBoard', '0002_alter_fboard_bfile1'),
        ('member', '0006_reservation_star'),
    ]

    operations = [
        migrations.AddField(
            model_name='fboard',
            name='like_members',
            field=models.ManyToManyField(default='', related_name='like_members', to='member.member'),
        ),
        migrations.AddField(
            model_name='fboard',
            name='member',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='fBoard_member', to='member.member'),
        ),
        migrations.DeleteModel(
            name='Reservation',
        ),
    ]
