# Generated by Django 5.1.3 on 2024-11-25 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_board_bimg'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board',
            name='bimg',
        ),
        migrations.AddField(
            model_name='board',
            name='bfile',
            field=models.ImageField(null=True, upload_to='board'),
        ),
    ]
