# Generated by Django 5.1.3 on 2024-12-13 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0005_member_addr_alter_member_agree1_alter_member_agree2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resPeople', models.IntegerField(default=0)),
                ('resMemo', models.TextField(default='', max_length=2000)),
                ('res', models.ManyToManyField(default='', related_name='res_members', to='member.member')),
            ],
        ),
        migrations.CreateModel(
            name='Star',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sDate', models.DateTimeField(auto_now=True)),
                ('star', models.ManyToManyField(default='', related_name='star_members', to='member.member')),
            ],
        ),
    ]
