# Generated by Django 5.1.3 on 2024-12-13 04:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0006_reservation_star'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='star',
            name='star',
        ),
        migrations.DeleteModel(
            name='Reservation',
        ),
        migrations.DeleteModel(
            name='Star',
        ),
    ]
